### ISSUE TITLE
Potentially Missing Questions

### ISSUE THREAD

**Issue by candacelax** [Yushi-Hu/tifa#3]
In the `question_gen.py` script, it looks like there are 12 in-context examples. In the paper, it says there are 15 examples. Any chance there are 2 missing?

**Comment by Yushi-Hu** [comment]
Good catch! In this codebase I subtract it to 12 because GPT-3.5 turbo's context window cannot support 15 examples. The original examples are here: [https://drive.google.com/file/d/1i5fpXkUFgB7w3ip2TtmS1xORi828ow6-/view?usp=sharing](https://drive.google.com/file/d/1i5fpXkUFgB7w3ip2TtmS1xORi828ow6-/view?usp=sharing) Feel free to use them

**Comment by candacelax** [comment]
Ah that makes sense, thanks!
